substitutions:
  devicename: m8-reference-ed
  friendly: "M8 Reference ED"
  # ESP32-C6 OpenThread TX power range in ESPHome: -15dB..20dB.
  thread_output_power: "8dB"

esphome:
  name: ${devicename}
  friendly_name: ${friendly}

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf
    log_level: INFO

logger:
  level: DEBUG
  hardware_uart: UART0
  deassert_rts_dtr: true

network:
  enable_ipv6: true

mdns:
  id: mdns_comp

openthread:
  mdns_id: mdns_comp
  device_type: MTD
  output_power: ${thread_output_power}
  force_dataset: true
  channel: 15
  pan_id: 0x1234
  ext_pan_id: 0x1111111122222222
  network_name: biparental-test
  network_key: 0x10112233445566778899AABBCCDDEEFF
  pskc: 0x112233445566778899AABBCCDDEEFF00
  mesh_local_prefix: "fd11:22:33:44::/64"
