substitutions:
  devicename: m8-biparental-ed
  friendly: "M8 Biparental ED"
  # ESP32-C6 OpenThread TX power range in ESPHome: -15dB..20dB.
  thread_output_power: "8dB"

packages:
  base: !include hwtest-ed.yaml
  tx_power_degradation: !include tx-power-degradation.yaml
